set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'
Plugin 'scrooloose/nerdcommenter'
Bundle "pangloss/vim-javascript"
Bundle 'mxw/vim-jsx'
Bundle 'w0rp/ale'
pundle "Valloric/YouCompleteMe"
Bundle 'tpope/vim-surround'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

" These are the tweaks I apply to YCM's config, you don't need them but they might help.
" YCM gives you popups and splits by default that some people might not like, so these should tidy it up a bit for you.
let g:ycm_add_preview_to_completeopt=0
let g:ycm_confirm_extra_conf=0
set completeopt-=preview
set omnifunc=syntaxcomplete#Complete

"don't care about vi
set nocompatible

"security
set modelines=0

"my tabs
set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab

" Use color syntax highlighting.
syntax on

" Options.
set ruler		" Show the line position at the bottom of the window
set scrolloff=1		" Minimum lines between cursor and window edge
set showcmd		" Show partially typed commands
set showmatch		" Show parentheses matching
set textwidth=80	" Maximum line width
set colorcolumn=80
set wrap
set writebackup		" Write temporary backup files in case we crash
set backspace=indent,eol,start
set encoding=utf-8
set ignorecase
set smartcase           " Search ignores case
set gdefault            " Global search
set t_Co=256

" Bracket matching
nnoremap ' % 
vnoremap ' %

"Scons
au BufNewFile,BufRead SConstruct setlocal ft=python

nnoremap <up> <nop>
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>
